namespace: baldeweg
name: base_collection
version: 1.0.0
readme: README.md
authors:
    - André Baldeweg <a@baldeweg.org>
description: Basic collection of roles.
license:
    - MIT
repository: https://github.com/abaldeweg/services
