name: Tag and release packages

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Name of the tag to create"
        required: true

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set the tag
        run: git tag -a ${{ inputs.tag_name }} -m "Version ${{ inputs.tag_name }}"
      - name: Push the tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin ${{ inputs.tag_name }}
