# build stage
FROM node:24-alpine AS builder

ARG VITE_BASE_URL="/"
ENV VITE_BASE_URL=$VITE_BASE_URL

WORKDIR /app

COPY . .

RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile
RUN pnpm -F <%= name %> build

# production stage
FROM httpd:2.4-alpine AS prod

ARG VITE_BASE_URL="/"
ENV VITE_BASE_URL=$VITE_BASE_URL

RUN addgroup -S appgroup \
	&& adduser -S appuser -G appgroup \
	&& chown -R appuser:appgroup /usr/local/apache2/logs /usr/local/apache2/htdocs${VITE_BASE_URL}

COPY ./apps/<%= name %>/docker/httpd.conf /usr/local/apache2/conf/httpd.conf

COPY --from=builder /app/apps/<%= name %>/dist /usr/local/apache2/htdocs${VITE_BASE_URL}

USER appuser

EXPOSE 80
