# Build stage
FROM golang:1.25 AS builder

ENV CGO_ENABLED=0

WORKDIR /app

COPY . .
RUN go mod download && go mod verify
RUN go build -v -o /app/apps/dist/<%= name %> ./apps/<%= name %>/app/main.go

# Production stage
FROM alpine:3.23 AS prod

RUN adduser -D -u 10001 appuser

WORKDIR /app

COPY --from=builder --chown=appuser:appuser /app/apps/dist/<%= name %> .

USER appuser

EXPOSE 8080

CMD ["./<%= name %>"]
