name: Tag and release packages

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Name of the tag to create"
        required: true

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - name: Set version in package.json
        run: |
          sed -i 's/"version": "[^"]*"/"version": "${{ inputs.tag_name }}"/g' packages/<%= name %>/package.json
      - name: Commit Version Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: update version"
          file_pattern: packages/<%= name %>/**/*
      - name: Push Changes
        run: git push origin HEAD
      - name: Tag the commit
        run: git tag -a ${{ inputs.tag_name }} -m "Version ${{ inputs.tag_name }}"
      - name: Push the tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin ${{ inputs.tag_name }}
