name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  - read
  - write
  - execute

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Install dependencies
        working-directory: ./module
        run: go mod tidy
      - name: Run tests
        working-directory: ./module
        run: go test ./...
