ARG VITE_BASE_URL

# build stage
FROM node:24-alpine as builder

ARG VITE_BASE_URL
ENV VITE_BASE_URL=$VITE_BASE_URL

WORKDIR /usr/app

COPY . .

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm -F <%= name %> build

# production stage
FROM httpd:2.4-alpine as prod

ARG VITE_BASE_URL
ENV VITE_BASE_URL=$VITE_BASE_URL

COPY ./packages/<%= name %>/docker/httpd.conf /usr/local/apache2/conf/httpd.conf

COPY --from=builder /usr/app/packages/<%= name %>/dist /usr/local/apache2/htdocs${VITE_BASE_URL}

RUN addgroup --system appgroup \
	&& adduser --system --ingroup appgroup appuser \
	&& chown -R appuser:appgroup /usr/local/apache2/htdocs${VITE_BASE_URL}
USER appuser

EXPOSE 80
