version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

release:
    disable: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    id: app_backup
    binary: app_backup

archives:
  - format: tar.gz
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  -
    package_name: app_backup
    section: misc
    description: "app_backup is a tool to extract and manage app IDs from ADB."
    maintainer: "André Baldeweg"
    formats:
      - deb

checksum:
  name_template: "checksums.txt"
