name: Test my-package

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    unit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v5
              with:
                  node-version: 24
            - name: Install pnpm
              run: npm install -g pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Run tests
              run: pnpm -F @baldeweg/create test
